### ISSUE TITLE
Enhancements collection from 0.5 betatesting

### ISSUE THREAD

**Issue by s-blu** [s-blu/writerey#35]
- [x] Cancel on dir creation
- [x] Hit enter to submit a dialog
- [ ] Error startup git/commit - maybe init call? Init commit can be removed! ==> #45
- [x] Newly created marker in tree dead
- [x] Changing a marker value range doesn't show up on dicument - maybe force rerender after being on marker page
- [x] Custom Git msg doesnt make it to BE
- [x] When switching to read more: last selected paragraph style isnt resetted (also true when switching write/review)
- [x] Have new Note expanded by default
- [ ] When doing BLOCK scoped formatting (i.e. setting header), editor jumps to top. Maybe a problem with the parent scrolling container? try to scroll editor itself and see if this helps ==> #39
- [ ] Additional save button for manual save? ==> #39
- [ ] No formatting available in notes :( ==> #44 
- [x] Clear only text on notes, leave the rest to its selected value
- [x] Lower Padding of Notes to save some space
- [x] Move Create Notes onto the top
